#!/bin/sh
fail() {
	/bin/echo "Failed"
		/bin/echo "$1"
		exec /bin/sh
}

/bin/mount -o remount,rw / /

PATH=/sbin:/system/sbin:/bin:/system/bin:/system/xbin:/system/xbin/bb:/data/local/bin

/bin/echo "Rootfs loaded."

/bin/mount -t proc proc /proc
/bin/mount -t sysfs sys /sys

echo 256 > /sys/devices/virtual/bdi/179:0/read_ahead_kb
echo 7 > /proc/sys/vm/laptop_mode
echo 90 > /proc/sys/vm/dirty_ratio
echo 60000 > /proc/sys/vm/dirty_expire_centisecs
echo 60000 > /proc/sys/vm/dirty_writeback_centisecs
MAKEDEVS
notnand=0

if [ $notnand = "0" ] ; then
  echo "running from NAND"
  /bin/mount -t yaffs2 /dev/block/mtdblock3 /system
  /bin/mount -t yaffs2 /dev/block/mtdblock4 /data
fi

cp -ar /init.etc/* /system/etc

LCDDENSITY=`/bin/grep -o "lcd.density=.*" /proc/cmdline | /bin/sed -e "s/.*lcd.density=//g" -e "s/ .*//g"`

if [ "$LCDDENSITY" != "" ] ; then
	DENS2=`grep lcd_density /system/etc/default.prop | sed -e 's/.*=//'`
	if [ "$LCDDENSITY" != "$DENS2" ]; then
		echo Setting ro.sf.lcd_density=$LCDDENSITY
		if [ -z "$DENS2" ]; then
			echo "ro.sf.lcd_density=$LCDDENSITY" >> /system/etc/default.prop
		else
			sed -i /lcd_density/s/=.*/=$LCDDENSITY/ /system/etc/default.prop
		fi
	fi
fi

KAISER=0
DIAMOND=0
WIFI_TI=0
WIFI_BCM=0
XPERIA=0
WVGA=0
HW=RHODIUM
DIAMOND=1
WIFI_BCM=1
WVGA=1

RCSCRIPT=""
RCCONFIG=""

echo "Gingerbread build detected"
RCSCRIPT="gingerbread"
RCCONFIG="gingerbread"

if [ "$LCDDENSITY" != "" ] ; then
	DENS2=`grep lcd_density /system/etc/default.prop | sed -e 's/.*=//'`
	if [ "$LCDDENSITY" != "$DENS2" ]; then
		echo Setting ro.sf.lcd_density=$LCDDENSITY
		if [ -z "$DENS2" ]; then
			echo "ro.sf.lcd_density=$LCDDENSITY" >> /system/etc/default.prop
		else
			sed -i /lcd_density/s/=.*/=$LCDDENSITY/ /system/etc/default.prop
		fi
	fi
fi

echo "using system/etc/$RCCONFIG.user.conf"

INITRC=`ls -l /init.rc | grep "$RCSCRIPT"`
if [ -z "$INITRC" ]; then
	echo "using /init.$RCSCRIPT.rc as init.rc"
	rm -f /init.rc
	ln -s "/init.cfg/init.$RCSCRIPT.rc" /init.rc
fi

if [ "$WIFI_TI" = "1" ] || [ "$WIFI_BCM" = "1" ];then
	if [ -e "/system/lib/modules/modules-$(uname -r).tar.gz" ] && ! `strings /lib/modules/mac80211.ko 2>/dev/null | grep -q "vermagic=$(uname -r)"`; then
		echo "Installing system/lib/modules/modules-$(uname -r).tar.gz"
		tar xzf /system/lib/modules/modules-$(uname -r).tar.gz -C /lib/modules
		ln -s /lib/modules /lib/modules/`uname -r`
	else
		echo "Modules already unpacked for this kernel version -- skipping installation of system/lib/modules/modules-$(uname -r).tar.gz"
	fi

	if [ -f /system/etc/wifi/wlan.ko ]; then
	cp -R /system/etc/wifi/* /lib/modules/
	rm /system/etc/wifi/wlan.ko
	depmod
	fi

	if [ "`grep -c ^wifi /system/etc/default.prop`" != "2" ]; then
		echo "wifi.interface = wlan0" >> /system/etc/default.prop
		echo "wifi.supplicant_scan_interval = 45" >> /system/etc/default.prop
	fi
fi


if [ ! -e /data/wifi-nvram.txt ]; then
cat /proc/calibration > /data/wifi-nvram.txt
fi

if [ -f /system/etc/gingerbread.user.conf ]; then
	/bin/userinit.sh -c /system/etc/gingerbread.user.conf
else
	echo "No user config files ($RCCONFIG) found in /system/etc"
fi

mount -tdebugfs none /dbgfs
#Activate baclight control
echo 3 > /sys/class/htc_hw/test
#Smooth scroll
echo 40 >/sys/devices/system/cpu/cpu0/cpufreq/ondemand/up_threshold
#Activate full charging
echo 2 > /dbgfs/htc_battery/charger_state

cp /init.etc/keymaps/default/*.kl /system/usr/keylayout/
cp /init.etc/keymaps/default/*.kcm* /system/usr/keychars/
LAYOUT=`/bin/grep ".*0*" /sys/class/htc_hw/machine_variant`
if [ $LAYOUT = "RHOD300" ] ; then
	echo "USING EXPERIMENTAL TILT2 LAYOUT"
	cp /init.etc/keymaps/rhod300/*.kl /system/usr/keylayout/
	cp /init.etc/keymaps/rhod300/*.kcm* /system/usr/keychars/

	cp -f /system/etc/audiofiles/gsm/AudioFilterTable.csv /system/etc/AudioFilterTable.csv
	cp -f /system/etc/audiofiles/gsm/AudioPara3_ATT.csv /system/etc/AudioPara3.csv
	cp -f /system/etc/audiofiles/gsm/AudioPreProcessTable.csv /system/etc/AudioPreProcessTable.csv


elif [ $LAYOUT = "RHOD100" ] ; then
	echo "USING EXPERIMENTAL RHOD100 LAYOUT (UK DEFAULT)"
	cp /init.etc/keymaps/rhod100/*.kl /system/usr/keylayout/
	cp /init.etc/keymaps/rhod100/*.kcm* /system/usr/keychars/
	cp -f /system/etc/audiofiles/gsm/AudioFilterTable.csv /system/etc/AudioFilterTable.csv
	cp -f /system/etc/audiofiles/gsm/AudioPara3.csv /system/etc/AudioPara3.csv
	cp -f /system/etc/audiofiles/gsm/AudioPreProcessTable.csv /system/etc/AudioPreProcessTable.csv

elif [ $LAYOUT = "RHOD210" ] ; then
	echo "USING EXPERIMENTAL RHOD210 LAYOUT"
	cp /init.etc/keymaps/rhod210/*.kl /system/usr/keylayout/
	cp /init.etc/keymaps/rhod210/*.kcm* /system/usr/keychars/
	cp -f /system/etc/audiofiles/gsm/AudioFilterTable.csv /system/etc/AudioFilterTable.csv
	cp -f /system/etc/audiofiles/gsm/AudioPara3_TMO.csv /system/etc/AudioPara3.csv
	cp -f /system/etc/audiofiles/gsm/AudioPreProcessTable.csv /system/etc/AudioPreProcessTable.csv

elif [ $LAYOUT = "RHOD400" ] ; then
	echo "USING EXPERIMENTAL RHOD400 LAYOUT"
	cp /init.etc/keymaps/rhod400/*.kl /system/usr/keylayout/
	cp /init.etc/keymaps/rhod400/*.kcm* /system/usr/keychars/
	cp -f /system/etc/audiofiles/cdma/AudioFilterTable.csv /system/etc/AudioFilterTable.csv
	cp -f /system/etc/audiofiles/cdma/AudioPara3.csv /system/etc/AudioPara3.csv
	cp -f /system/etc/audiofiles/cdma/AudioPreProcessTable.csv /system/etc/AudioPreProcessTable.csv

elif [ $LAYOUT = "RHOD500" ] ; then
	echo "USING EXPERIMENTAL RHOD500 LAYOUT"
	cp /init.etc/keymaps/rhod500/*.kl /system/usr/keylayout/
	cp /init.etc/keymaps/rhod500/*.kcm* /system/usr/keychars/
	cp -f /system/etc/audiofiles/cdma/AudioFilterTable.csv /system/etc/AudioFilterTable.csv
	cp -f /system/etc/audiofiles/cdma/AudioPara3.csv /system/etc/AudioPara3.csv
	cp -f /system/etc/audiofiles/cdma/AudioPreProcessTable.csv /system/etc/AudioPreProcessTable.csv
else
    echo "CAN'T DETERMINE RHODIUM VARIANT TYPE"
	cat /sys/class/htc_hw/machine_variant
fi
chown 1001:1005 /system/etc/AudioPara3.csv
chmod 0444 /system/etc/AudioPara3.csv
chmod 666 /system/etc/AudioFilterTable.csv
chmod 666 /system/etc/AudioPreProcessTable.csv
chmod 666 /system/usr/keylayout/*.*
chmod 666 /system/usr/keychars/*.*
mount -o remount,ro /system

## Ts Calibration
for i in /sys/class/input/input* ; do
        if [ "`cat $i/name`" = "tssc-manager" ] ; then
                touchscreendir=$i
                echo "Touchscreen device directory is $i"
        fi
done

if [ -f /data/ts-calibration ] ; then
        echo "Using Saved Touchscreen Calibration"
        echo 128,128,1903,128,128,1907,1903,1907,1024,1024 > $touchscreendir/calibration_screen
        cat /data/ts-calibration > $touchscreendir/calibration_points
else
        echo "Using Default Calibration Values"
	cat /sys/android_tp_cal/tp_cal > /data/ts-calibration
        cat /data/ts-calibration > $touchscreendir/calibration_points
fi

mkdir /dev/msm_camera
mknod /dev/msm_camera/control0 c 250 0
mknod /dev/msm_camera/config0 c 250 1
mknod /dev/msm_camera/frame0 c 250 2

# Transition sequence for FRX06->FRX07 (eth0/tiwlan0 renamed)
if [ -f "/data/misc/wifi/wpa_supplicant.conf" ]
then
	sed -i -e 's:=\(tiwlan0\|eth0\):=wlan0:' /data/misc/wifi/wpa_supplicant.conf
	chown 1000:1010 /data/misc/wifi/wpa_supplicant.conf
fi

exec /init.android
