#!/bin/sh
if [ ! -e /data/wifi-calibration ]; then
	insmod /lib/modules/mtdchar.ko
	mknod /dev/mtd/mtd0ro c 90 1
	mkdir /lib/modules/$(uname -r)
	dd if=/dev/mtd/mtd0ro of=/tmp/tempcal bs=8192 count=1 skip=4736
	rm /dev/mtd/mtd0ro
	rmmod mtdchar
	rmdir /lib/modules/$(uname -r)
	dd if=/tmp/tempcal of=/data/wifi-calibration bs=1 count=752 skip=64
	rm /sdcard/tempcal
fi
/etc/wifi/wlan_loader -f /etc/wifi/Fw1251r1c.bin -e /data/wifi-calibration -i /etc/wifi/tiwlan.ini
